# Generated by Django 4.2.20 on 2025-04-23 18:00

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('weightloss', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Ингредиенты'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Инструкции'),
        ),
        migrations.AlterField(
            model_name='successstory',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='История'),
        ),
    ]
