# Generated by Django 4.2.20 on 2025-04-24 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('weightloss', '0006_recipe_author_recipe_is_user_submitted_recipe_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FAQ',
        ),
        migrations.DeleteModel(
            name='SuccessStory',
        ),
        migrations.AlterModelOptions(
            name='challenge',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-created_on']},
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile_pic',
            new_name='avatar',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='updated_on',
        ),
        migrations.RemoveField(
            model_name='forumpost',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_user_submitted',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='is_user_submitted',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='current_weight',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='goal_weight',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='starting_weight',
        ),
        migrations.AddField(
            model_name='recipe',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='target_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='duration',
            field=models.PositiveIntegerField(help_text='Продолжительность в днях'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_posts', to='weightloss.forumtopic'),
        ),
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='carbs',
            field=models.PositiveIntegerField(help_text='Углеводы в граммах'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='fat',
            field=models.PositiveIntegerField(help_text='Жиры в граммах'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='preparation_time',
            field=models.PositiveIntegerField(help_text='Время в минутах'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='protein',
            field=models.PositiveIntegerField(help_text='Белки в граммах'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='status',
            field=models.CharField(choices=[('draft', 'На рассмотрении'), ('published', 'Опубликовано'), ('rejected', 'Отклонено')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='height',
            field=models.PositiveIntegerField(blank=True, help_text='Рост в сантиметрах', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
