# Generated by Django 4.2.20 on 2025-04-24 15:10

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('weightloss', '0008_remove_userprofile_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Описание'),
        ),
    ]
