# Generated by Django 4.2.20 on 2025-04-24 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weightloss', '0009_alter_challenge_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='weightloss.forumpost'),
        ),
    ]
