# Generated by Django 4.2.20 on 2025-04-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightloss', '0010_forumpost_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано'), ('pending', 'На модерации'), ('rejected', 'Отклонено')], default='draft', max_length=10),
        ),
    ]
