# Generated by Django 4.2.20 on 2025-04-29 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('weightloss', '0014_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_vip',
            field=models.BooleanField(default=False, verbose_name='VIP статус'),
        ),
        migrations.CreateModel(
            name='VIPPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('content', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vip_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'VIP статья',
                'verbose_name_plural': 'VIP статьи',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='VIPComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vip_comments', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='weightloss.vipcomment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='weightloss.vippost')),
            ],
            options={
                'verbose_name': 'VIP комментарий',
                'verbose_name_plural': 'VIP комментарии',
                'ordering': ['created_on'],
            },
        ),
    ]
