# Generated by Django 4.2.20 on 2025-04-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightloss', '0015_userprofile_is_vip_vippost_vipcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='vip_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Срок действия VIP статуса'),
        ),
    ]
