# Generated by Django 4.2.20 on 2025-04-29 18:53

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('weightloss', '0016_userprofile_vip_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vipcomment',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='vippost',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Содержание'),
        ),
    ]
