# Generated by Django 4.2.20 on 2025-05-01 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightloss', '0017_alter_vipcomment_content_alter_vippost_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.CharField(max_length=200, verbose_name='Тема')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
            ],
            options={
                'verbose_name': 'Сообщение обратной связи',
                'verbose_name_plural': 'Сообщения обратной связи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='challenge',
            options={'ordering': ['-created_on'], 'verbose_name': 'Челлендж', 'verbose_name_plural': 'Челленджи'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_on'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='forumcategory',
            options={'ordering': ['order'], 'verbose_name': 'Категория форума', 'verbose_name_plural': 'Категории форума'},
        ),
        migrations.AlterModelOptions(
            name='forumpost',
            options={'ordering': ['created_on'], 'verbose_name': 'Сообщение форума', 'verbose_name_plural': 'Сообщения форума'},
        ),
        migrations.AlterModelOptions(
            name='forumtopic',
            options={'ordering': ['-is_pinned', '-updated_on'], 'verbose_name': 'Тема форума', 'verbose_name_plural': 'Темы форума'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Уведомление', 'verbose_name_plural': 'Уведомления'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_on'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-created_on'], 'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
        migrations.AlterModelOptions(
            name='recipecomment',
            options={'ordering': ['created_on'], 'verbose_name': 'Комментарий к рецепту', 'verbose_name_plural': 'Комментарии к рецептам'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Профиль пользователя', 'verbose_name_plural': 'Профили пользователей'},
        ),
    ]
