# Generated by Django 4.2.20 on 2025-05-17 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('weightloss', '0018_contactmessage_alter_category_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название продукта')),
                ('calories', models.PositiveIntegerField(verbose_name='Калории на 100г')),
                ('protein', models.FloatField(verbose_name='Белки на 100г (г)')),
                ('fats', models.FloatField(verbose_name='Жиры на 100г (г)')),
                ('carbs', models.FloatField(verbose_name='Углеводы на 100г (г)')),
                ('is_custom', models.BooleanField(default=False, verbose_name='Пользовательский продукт')),
                ('image', models.ImageField(blank=True, null=True, upload_to='foods/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(blank=True, help_text="Font Awesome класс, напр. 'fa-apple'", max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Категория продуктов',
                'verbose_name_plural': 'Категории продуктов',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Завтрак'), ('lunch', 'Обед'), ('dinner', 'Ужин'), ('snack', 'Перекус')], max_length=20, verbose_name='Тип приема пищи')),
                ('day_of_week', models.PositiveIntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота'), (7, 'Воскресенье')], verbose_name='День недели')),
            ],
            options={
                'verbose_name': 'Прием пищи',
                'verbose_name_plural': 'Приемы пищи',
                'ordering': ['day_of_week', 'meal_type'],
            },
        ),
        migrations.CreateModel(
            name='NutritionGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('male', 'Мужчина'), ('female', 'Женщина')], max_length=10, verbose_name='Пол')),
                ('age', models.PositiveIntegerField(verbose_name='Возраст')),
                ('height', models.PositiveIntegerField(verbose_name='Рост (см)')),
                ('weight', models.FloatField(verbose_name='Вес (кг)')),
                ('activity_level', models.CharField(choices=[('sedentary', 'Сидячий образ жизни'), ('light', 'Тренировки 1-3 раза в неделю'), ('moderate', 'Тренировки 3-5 раз в неделю'), ('active', 'Тренировки 6-7 раз в неделю'), ('very_active', 'Тяжелая физическая работа или 2 тренировки в день')], max_length=20, verbose_name='Уровень активности')),
                ('goal', models.CharField(choices=[('maintain', 'Поддерживать вес'), ('lose_slow', 'Медленное похудение (-10%)'), ('lose_medium', 'Среднее похудение (-15%)'), ('lose_fast', 'Быстрое похудение (-20%)'), ('gain_slow', 'Медленный набор (+10%)'), ('gain_medium', 'Средний набор (+15%)'), ('gain_fast', 'Быстрый набор (+20%)')], max_length=20, verbose_name='Цель')),
                ('base_calories', models.PositiveIntegerField(verbose_name='Базовые калории')),
                ('target_calories', models.PositiveIntegerField(verbose_name='Целевые калории')),
                ('protein_per_kg', models.FloatField(verbose_name='Белки на кг веса')),
                ('protein_daily', models.FloatField(verbose_name='Белки в день (г)')),
                ('fats_per_kg', models.FloatField(verbose_name='Жиры на кг веса')),
                ('fats_daily', models.FloatField(verbose_name='Жиры в день (г)')),
                ('carbs_daily', models.FloatField(verbose_name='Углеводы в день (г)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_goals', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Цель по питанию',
                'verbose_name_plural': 'Цели по питанию',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название плана')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('nutrition_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plans', to='weightloss.nutritiongoal', verbose_name='Цель по питанию')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plans', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'План питания',
                'verbose_name_plural': 'Планы питания',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MealItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='Количество (г)')),
                ('calories', models.PositiveIntegerField(editable=False, verbose_name='Калории')),
                ('protein', models.FloatField(editable=False, verbose_name='Белки (г)')),
                ('fats', models.FloatField(editable=False, verbose_name='Жиры (г)')),
                ('carbs', models.FloatField(editable=False, verbose_name='Углеводы (г)')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_items', to='weightloss.food', verbose_name='Продукт')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_items', to='weightloss.meal', verbose_name='Прием пищи')),
            ],
            options={
                'verbose_name': 'Продукт в рационе',
                'verbose_name_plural': 'Продукты в рационе',
            },
        ),
        migrations.AddField(
            model_name='meal',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='weightloss.mealplan', verbose_name='План питания'),
        ),
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='weightloss.foodcategory', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='food',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_foods', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
